# Generated by Django 4.2.14 on 2024-08-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_published',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='title',
        ),
    ]
