# Generated by Django 4.2.14 on 2024-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0004_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Book description'),
        ),
    ]
