# Generated by Django 4.2.14 on 2024-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0005_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
