# Generated by Django 4.2.14 on 2024-10-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0009_remove_rating_rating_userbook_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBook',
            new_name='UserBookInteraction',
        ),
    ]
