# Generated by Django 4.2.14 on 2024-10-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0011_rename_user_profile_userbookinteraction_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookinteraction',
            unique_together={('profile', 'book')},
        ),
    ]
