# Generated by Django 4.2.14 on 2024-10-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_check', '0012_alter_userbookinteraction_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookinteraction',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='userbookinteraction',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
